[package]
name = "irpc-iroh"
version = "0.1.0"
edition = "2024"
authors = ["Rüdiger Klaehn <rklaehn@protonmail.com>", "n0 team"]
keywords = ["api", "protocol", "network", "rpc"]
categories = ["network-programming"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/irpc"
description = "Iroh transport for irpc"

[dependencies]
anyhow = "1.0.97"
iroh = "0.34.0"
irpc = { version = "0.1.0", path = ".." }
tokio = { version = "1.44.1", default-features = false, features = ["sync"] }
serde = { version = "1", default-features = false }
tracing = { version = "0.1.41" }
postcard = { version = "1.1.1", features = ["alloc", "use-std"] }

[dev-dependencies]
n0-future = { version = "0.1.2", default-features = false }
irpc-derive = { version = "0.1.0", path = "../irpc-derive" }
tracing-subscriber = { version = "0.3.19", features = ["fmt"] }
