[package]
name = "irpc-iroh"
version = "0.1.0"
edition = "2024"
authors = ["Rüdiger Klaehn <rklaehn@protonmail.com>", "n0 team"]
keywords = ["api", "protocol", "network", "rpc"]
categories = ["network-programming"]
license = "Apache-2.0/MIT"
repository = "https://github.com/n0-computer/irpc"
description = "Iroh transport for irpc"

[dependencies]
anyhow = { workspace = true }
iroh = { workspace = true }
tokio = { workspace = true, features = ["sync"] }
tracing = { workspace = true }
serde = { workspace = true }
postcard = { workspace = true, features = ["alloc", "use-std"] }
irpc = { version = "0.1.0", path = ".." }

[dev-dependencies]
n0-future = { workspace = true }
tracing-subscriber = { workspace = true, features = ["fmt"] }
irpc-derive = { version = "0.1.0", path = "../irpc-derive" }
