//! Span context propagation for remote RPC calls
//!
//! This module provides the `SpanContextCarrier` type for propagating trace context
//! across remote boundaries. The type is always available when `rpc` feature is enabled,
//! but actual OpenTelemetry integration requires the `tracing-opentelemetry` feature.
//!
//! The propagated context is scoped to a single request handler via a tokio task-local,
//! installed by the dispatch loop in `handle_connection`. This isolates concurrent
//! requests from each other and is robust to thread migration across `.await` points.

use std::{collections::HashMap, future::Future};

use serde::{Deserialize, Serialize};

#[cfg(feature = "tracing-opentelemetry")]
tokio::task_local! {
    static SPAN_CONTEXT: opentelemetry::Context;
}

/// Carrier for propagating span context across RPC boundaries using W3C Trace Context format.
///
/// This type is always available for serialization purposes. When the
/// `tracing-opentelemetry` feature is enabled, it can extract/inject actual
/// OpenTelemetry trace context. Without that feature, it simply serializes as an
/// empty map.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct SpanContextCarrier {
    headers: HashMap<String, String>,
}

#[cfg(feature = "tracing-opentelemetry")]
impl opentelemetry::propagation::Injector for SpanContextCarrier {
    fn set(&mut self, key: &str, value: String) {
        self.headers.insert(key.to_string(), value);
    }
}

#[cfg(feature = "tracing-opentelemetry")]
impl opentelemetry::propagation::Extractor for SpanContextCarrier {
    fn get(&self, key: &str) -> Option<&str> {
        self.headers.get(key).map(|v| v.as_str())
    }

    fn keys(&self) -> Vec<&str> {
        self.headers.keys().map(|k| k.as_str()).collect()
    }
}

impl SpanContextCarrier {
    /// Create a carrier from the current OpenTelemetry context.
    ///
    /// When `tracing-opentelemetry` feature is enabled, this extracts the current
    /// trace context. Without the feature, this returns an empty carrier.
    #[cfg(feature = "tracing-opentelemetry")]
    pub fn from_current() -> Self {
        use opentelemetry::global;
        use tracing_opentelemetry::OpenTelemetrySpanExt;
        let mut carrier = Self::default();
        // Get the OTel context from the current tracing span, not from
        // opentelemetry::Context::current(). The tracing-opentelemetry layer
        // stores OTel spans inside tracing spans, so the thread-local OTel
        // context won't have the right span.
        let ctx = tracing::Span::current().context();
        global::get_text_map_propagator(|prop| {
            prop.inject_context(&ctx, &mut carrier);
        });
        carrier
    }

    #[cfg(not(feature = "tracing-opentelemetry"))]
    pub fn from_current() -> Self {
        Self::default()
    }

    /// Extract an OpenTelemetry context from this carrier.
    #[cfg(feature = "tracing-opentelemetry")]
    pub fn to_context(&self) -> opentelemetry::Context {
        use opentelemetry::global;
        global::get_text_map_propagator(|prop| {
            prop.extract_with_context(&opentelemetry::Context::current(), self)
        })
    }
}

/// Run `fut` with `carrier`'s context installed as the per-task scope read by
/// [`set_span_parent_from_remote`].
///
/// Used by transport implementations (`irpc::rpc`, `irpc-iroh`) to wrap a single
/// request handler. Most users will not call this directly.
pub async fn scope_remote<F: Future>(carrier: Option<SpanContextCarrier>, fut: F) -> F::Output {
    #[cfg(feature = "tracing-opentelemetry")]
    if let Some(carrier) = carrier {
        return SPAN_CONTEXT.scope(carrier.to_context(), fut).await;
    }
    let _ = carrier;
    fut.await
}

/// Set the parent of a span from the propagated remote context, if one is in scope.
///
/// Called by the code generated by `rpc_requests(span_propagation)`. Looks up the
/// task-local installed by the dispatch loop; no-op outside that scope.
pub fn set_span_parent_from_remote(span: &tracing::Span) {
    #[cfg(feature = "tracing-opentelemetry")]
    {
        let _ = SPAN_CONTEXT.try_with(|ctx| {
            use tracing_opentelemetry::OpenTelemetrySpanExt;
            let _ = span.set_parent(ctx.clone());
        });
    }
    let _ = span;
}
